ALTER TABLE "fleet_telemetry_row" DROP CONSTRAINT "fleet_telemetry_row_ewar_ck";--> statement-breakpoint
ALTER TABLE "fleet_telemetry_row" ALTER COLUMN "publication_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "fleet_telemetry_row" ADD COLUMN "outgoing_dps" integer;--> statement-breakpoint
ALTER TABLE "fleet_telemetry_row" ADD COLUMN "incoming_dps" integer;--> statement-breakpoint
ALTER TABLE "fleet_telemetry_row" ADD COLUMN "sampled_at_ms" bigint NOT NULL;--> statement-breakpoint
ALTER TABLE "fleet_telemetry_row" ADD COLUMN "activity_origin_ms" bigint NOT NULL;--> statement-breakpoint
ALTER TABLE "fleet_telemetry_row" ADD COLUMN "effects" jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "fleet_telemetry_row" DROP COLUMN "dps";--> statement-breakpoint
ALTER TABLE "fleet_telemetry_row" DROP COLUMN "ewar";--> statement-breakpoint
ALTER TABLE "fleet_telemetry_row" ADD CONSTRAINT "fleet_telemetry_row_dps_ck" CHECK (
      ("fleet_telemetry_row"."outgoing_dps" IS NULL OR "fleet_telemetry_row"."outgoing_dps" BETWEEN 0 AND 10000000) AND
      ("fleet_telemetry_row"."incoming_dps" IS NULL OR "fleet_telemetry_row"."incoming_dps" BETWEEN 0 AND 10000000));--> statement-breakpoint
ALTER TABLE "fleet_telemetry_row" ADD CONSTRAINT "fleet_telemetry_row_origins_ck" CHECK (
      "fleet_telemetry_row"."sampled_at_ms" BETWEEN 0 AND 9007199254740991 AND
      "fleet_telemetry_row"."activity_origin_ms" BETWEEN 0 AND "fleet_telemetry_row"."sampled_at_ms" AND
      "fleet_telemetry_row"."sampled_at_ms" - "fleet_telemetry_row"."activity_origin_ms" < 30000);--> statement-breakpoint
ALTER TABLE "fleet_telemetry_row" ADD CONSTRAINT "fleet_telemetry_row_publication_ck" CHECK (
      "fleet_telemetry_row"."publication_id"::text ~ '^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$');--> statement-breakpoint
ALTER TABLE "fleet_telemetry_row" ADD CONSTRAINT "fleet_telemetry_row_effects_ck" CHECK ((CASE
      WHEN jsonb_typeof("fleet_telemetry_row"."effects") = 'array' THEN
        jsonb_array_length("fleet_telemetry_row"."effects") <= 3 AND
        (("fleet_telemetry_row"."effects"->0) IS NULL OR (CASE WHEN
            jsonb_typeof(("fleet_telemetry_row"."effects"->0)) = 'object' AND
            jsonb_typeof((("fleet_telemetry_row"."effects"->0)->'observations')) = 'array' THEN
            ("fleet_telemetry_row"."effects"->0) - 'kind' - 'observations' = '{}'::jsonb AND
            ("fleet_telemetry_row"."effects"->0)->>'kind' IN ('SCRAM', 'POINT', 'NEUT') AND
            true AND
            jsonb_array_length((("fleet_telemetry_row"."effects"->0)->'observations')) BETWEEN 1 AND 9 AND
            jsonb_array_length(jsonb_path_query_array((("fleet_telemetry_row"."effects"->0)->'observations'), '$[*] ? (@.name != null)')) <= 8 AND
            (("fleet_telemetry_row"."effects"->0)->>'kind' <> 'NEUT' OR (jsonb_array_length((("fleet_telemetry_row"."effects"->0)->'observations')) = 1 AND (("fleet_telemetry_row"."effects"->0)->'observations')->0->'name' = 'null'::jsonb)) AND
            (((("fleet_telemetry_row"."effects"->0)->'observations')->0) IS NULL OR (CASE WHEN
                jsonb_typeof(((("fleet_telemetry_row"."effects"->0)->'observations')->0)) = 'object' AND jsonb_typeof(((("fleet_telemetry_row"."effects"->0)->'observations')->0)->'origin_ms') = 'number' THEN
                ((("fleet_telemetry_row"."effects"->0)->'observations')->0) - 'name' - 'origin_ms' = '{}'::jsonb AND
                (((("fleet_telemetry_row"."effects"->0)->'observations')->0)->'name' = 'null'::jsonb OR (jsonb_typeof(((("fleet_telemetry_row"."effects"->0)->'observations')->0)->'name') = 'string' AND length(((("fleet_telemetry_row"."effects"->0)->'observations')->0)->>'name') BETWEEN 1 AND 64 AND octet_length(((("fleet_telemetry_row"."effects"->0)->'observations')->0)->>'name') <= 256)) AND
                (((("fleet_telemetry_row"."effects"->0)->'observations')->0)->>'origin_ms')::numeric = trunc((((("fleet_telemetry_row"."effects"->0)->'observations')->0)->>'origin_ms')::numeric) AND (((("fleet_telemetry_row"."effects"->0)->'observations')->0)->>'origin_ms')::numeric BETWEEN 0 AND "fleet_telemetry_row"."activity_origin_ms" AND
                "fleet_telemetry_row"."sampled_at_ms" - (((("fleet_telemetry_row"."effects"->0)->'observations')->0)->>'origin_ms')::numeric < 30000
                
                ELSE false END)) AND (((("fleet_telemetry_row"."effects"->0)->'observations')->1) IS NULL OR (CASE WHEN
                jsonb_typeof(((("fleet_telemetry_row"."effects"->0)->'observations')->1)) = 'object' AND jsonb_typeof(((("fleet_telemetry_row"."effects"->0)->'observations')->1)->'origin_ms') = 'number' THEN
                ((("fleet_telemetry_row"."effects"->0)->'observations')->1) - 'name' - 'origin_ms' = '{}'::jsonb AND
                (((("fleet_telemetry_row"."effects"->0)->'observations')->1)->'name' = 'null'::jsonb OR (jsonb_typeof(((("fleet_telemetry_row"."effects"->0)->'observations')->1)->'name') = 'string' AND length(((("fleet_telemetry_row"."effects"->0)->'observations')->1)->>'name') BETWEEN 1 AND 64 AND octet_length(((("fleet_telemetry_row"."effects"->0)->'observations')->1)->>'name') <= 256)) AND
                (((("fleet_telemetry_row"."effects"->0)->'observations')->1)->>'origin_ms')::numeric = trunc((((("fleet_telemetry_row"."effects"->0)->'observations')->1)->>'origin_ms')::numeric) AND (((("fleet_telemetry_row"."effects"->0)->'observations')->1)->>'origin_ms')::numeric BETWEEN 0 AND "fleet_telemetry_row"."activity_origin_ms" AND
                "fleet_telemetry_row"."sampled_at_ms" - (((("fleet_telemetry_row"."effects"->0)->'observations')->1)->>'origin_ms')::numeric < 30000
                AND ((("fleet_telemetry_row"."effects"->0)->'observations')->1)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->0->'name'
                ELSE false END)) AND (((("fleet_telemetry_row"."effects"->0)->'observations')->2) IS NULL OR (CASE WHEN
                jsonb_typeof(((("fleet_telemetry_row"."effects"->0)->'observations')->2)) = 'object' AND jsonb_typeof(((("fleet_telemetry_row"."effects"->0)->'observations')->2)->'origin_ms') = 'number' THEN
                ((("fleet_telemetry_row"."effects"->0)->'observations')->2) - 'name' - 'origin_ms' = '{}'::jsonb AND
                (((("fleet_telemetry_row"."effects"->0)->'observations')->2)->'name' = 'null'::jsonb OR (jsonb_typeof(((("fleet_telemetry_row"."effects"->0)->'observations')->2)->'name') = 'string' AND length(((("fleet_telemetry_row"."effects"->0)->'observations')->2)->>'name') BETWEEN 1 AND 64 AND octet_length(((("fleet_telemetry_row"."effects"->0)->'observations')->2)->>'name') <= 256)) AND
                (((("fleet_telemetry_row"."effects"->0)->'observations')->2)->>'origin_ms')::numeric = trunc((((("fleet_telemetry_row"."effects"->0)->'observations')->2)->>'origin_ms')::numeric) AND (((("fleet_telemetry_row"."effects"->0)->'observations')->2)->>'origin_ms')::numeric BETWEEN 0 AND "fleet_telemetry_row"."activity_origin_ms" AND
                "fleet_telemetry_row"."sampled_at_ms" - (((("fleet_telemetry_row"."effects"->0)->'observations')->2)->>'origin_ms')::numeric < 30000
                AND ((("fleet_telemetry_row"."effects"->0)->'observations')->2)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->0->'name' AND ((("fleet_telemetry_row"."effects"->0)->'observations')->2)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->1->'name'
                ELSE false END)) AND (((("fleet_telemetry_row"."effects"->0)->'observations')->3) IS NULL OR (CASE WHEN
                jsonb_typeof(((("fleet_telemetry_row"."effects"->0)->'observations')->3)) = 'object' AND jsonb_typeof(((("fleet_telemetry_row"."effects"->0)->'observations')->3)->'origin_ms') = 'number' THEN
                ((("fleet_telemetry_row"."effects"->0)->'observations')->3) - 'name' - 'origin_ms' = '{}'::jsonb AND
                (((("fleet_telemetry_row"."effects"->0)->'observations')->3)->'name' = 'null'::jsonb OR (jsonb_typeof(((("fleet_telemetry_row"."effects"->0)->'observations')->3)->'name') = 'string' AND length(((("fleet_telemetry_row"."effects"->0)->'observations')->3)->>'name') BETWEEN 1 AND 64 AND octet_length(((("fleet_telemetry_row"."effects"->0)->'observations')->3)->>'name') <= 256)) AND
                (((("fleet_telemetry_row"."effects"->0)->'observations')->3)->>'origin_ms')::numeric = trunc((((("fleet_telemetry_row"."effects"->0)->'observations')->3)->>'origin_ms')::numeric) AND (((("fleet_telemetry_row"."effects"->0)->'observations')->3)->>'origin_ms')::numeric BETWEEN 0 AND "fleet_telemetry_row"."activity_origin_ms" AND
                "fleet_telemetry_row"."sampled_at_ms" - (((("fleet_telemetry_row"."effects"->0)->'observations')->3)->>'origin_ms')::numeric < 30000
                AND ((("fleet_telemetry_row"."effects"->0)->'observations')->3)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->0->'name' AND ((("fleet_telemetry_row"."effects"->0)->'observations')->3)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->1->'name' AND ((("fleet_telemetry_row"."effects"->0)->'observations')->3)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->2->'name'
                ELSE false END)) AND (((("fleet_telemetry_row"."effects"->0)->'observations')->4) IS NULL OR (CASE WHEN
                jsonb_typeof(((("fleet_telemetry_row"."effects"->0)->'observations')->4)) = 'object' AND jsonb_typeof(((("fleet_telemetry_row"."effects"->0)->'observations')->4)->'origin_ms') = 'number' THEN
                ((("fleet_telemetry_row"."effects"->0)->'observations')->4) - 'name' - 'origin_ms' = '{}'::jsonb AND
                (((("fleet_telemetry_row"."effects"->0)->'observations')->4)->'name' = 'null'::jsonb OR (jsonb_typeof(((("fleet_telemetry_row"."effects"->0)->'observations')->4)->'name') = 'string' AND length(((("fleet_telemetry_row"."effects"->0)->'observations')->4)->>'name') BETWEEN 1 AND 64 AND octet_length(((("fleet_telemetry_row"."effects"->0)->'observations')->4)->>'name') <= 256)) AND
                (((("fleet_telemetry_row"."effects"->0)->'observations')->4)->>'origin_ms')::numeric = trunc((((("fleet_telemetry_row"."effects"->0)->'observations')->4)->>'origin_ms')::numeric) AND (((("fleet_telemetry_row"."effects"->0)->'observations')->4)->>'origin_ms')::numeric BETWEEN 0 AND "fleet_telemetry_row"."activity_origin_ms" AND
                "fleet_telemetry_row"."sampled_at_ms" - (((("fleet_telemetry_row"."effects"->0)->'observations')->4)->>'origin_ms')::numeric < 30000
                AND ((("fleet_telemetry_row"."effects"->0)->'observations')->4)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->0->'name' AND ((("fleet_telemetry_row"."effects"->0)->'observations')->4)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->1->'name' AND ((("fleet_telemetry_row"."effects"->0)->'observations')->4)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->2->'name' AND ((("fleet_telemetry_row"."effects"->0)->'observations')->4)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->3->'name'
                ELSE false END)) AND (((("fleet_telemetry_row"."effects"->0)->'observations')->5) IS NULL OR (CASE WHEN
                jsonb_typeof(((("fleet_telemetry_row"."effects"->0)->'observations')->5)) = 'object' AND jsonb_typeof(((("fleet_telemetry_row"."effects"->0)->'observations')->5)->'origin_ms') = 'number' THEN
                ((("fleet_telemetry_row"."effects"->0)->'observations')->5) - 'name' - 'origin_ms' = '{}'::jsonb AND
                (((("fleet_telemetry_row"."effects"->0)->'observations')->5)->'name' = 'null'::jsonb OR (jsonb_typeof(((("fleet_telemetry_row"."effects"->0)->'observations')->5)->'name') = 'string' AND length(((("fleet_telemetry_row"."effects"->0)->'observations')->5)->>'name') BETWEEN 1 AND 64 AND octet_length(((("fleet_telemetry_row"."effects"->0)->'observations')->5)->>'name') <= 256)) AND
                (((("fleet_telemetry_row"."effects"->0)->'observations')->5)->>'origin_ms')::numeric = trunc((((("fleet_telemetry_row"."effects"->0)->'observations')->5)->>'origin_ms')::numeric) AND (((("fleet_telemetry_row"."effects"->0)->'observations')->5)->>'origin_ms')::numeric BETWEEN 0 AND "fleet_telemetry_row"."activity_origin_ms" AND
                "fleet_telemetry_row"."sampled_at_ms" - (((("fleet_telemetry_row"."effects"->0)->'observations')->5)->>'origin_ms')::numeric < 30000
                AND ((("fleet_telemetry_row"."effects"->0)->'observations')->5)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->0->'name' AND ((("fleet_telemetry_row"."effects"->0)->'observations')->5)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->1->'name' AND ((("fleet_telemetry_row"."effects"->0)->'observations')->5)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->2->'name' AND ((("fleet_telemetry_row"."effects"->0)->'observations')->5)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->3->'name' AND ((("fleet_telemetry_row"."effects"->0)->'observations')->5)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->4->'name'
                ELSE false END)) AND (((("fleet_telemetry_row"."effects"->0)->'observations')->6) IS NULL OR (CASE WHEN
                jsonb_typeof(((("fleet_telemetry_row"."effects"->0)->'observations')->6)) = 'object' AND jsonb_typeof(((("fleet_telemetry_row"."effects"->0)->'observations')->6)->'origin_ms') = 'number' THEN
                ((("fleet_telemetry_row"."effects"->0)->'observations')->6) - 'name' - 'origin_ms' = '{}'::jsonb AND
                (((("fleet_telemetry_row"."effects"->0)->'observations')->6)->'name' = 'null'::jsonb OR (jsonb_typeof(((("fleet_telemetry_row"."effects"->0)->'observations')->6)->'name') = 'string' AND length(((("fleet_telemetry_row"."effects"->0)->'observations')->6)->>'name') BETWEEN 1 AND 64 AND octet_length(((("fleet_telemetry_row"."effects"->0)->'observations')->6)->>'name') <= 256)) AND
                (((("fleet_telemetry_row"."effects"->0)->'observations')->6)->>'origin_ms')::numeric = trunc((((("fleet_telemetry_row"."effects"->0)->'observations')->6)->>'origin_ms')::numeric) AND (((("fleet_telemetry_row"."effects"->0)->'observations')->6)->>'origin_ms')::numeric BETWEEN 0 AND "fleet_telemetry_row"."activity_origin_ms" AND
                "fleet_telemetry_row"."sampled_at_ms" - (((("fleet_telemetry_row"."effects"->0)->'observations')->6)->>'origin_ms')::numeric < 30000
                AND ((("fleet_telemetry_row"."effects"->0)->'observations')->6)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->0->'name' AND ((("fleet_telemetry_row"."effects"->0)->'observations')->6)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->1->'name' AND ((("fleet_telemetry_row"."effects"->0)->'observations')->6)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->2->'name' AND ((("fleet_telemetry_row"."effects"->0)->'observations')->6)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->3->'name' AND ((("fleet_telemetry_row"."effects"->0)->'observations')->6)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->4->'name' AND ((("fleet_telemetry_row"."effects"->0)->'observations')->6)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->5->'name'
                ELSE false END)) AND (((("fleet_telemetry_row"."effects"->0)->'observations')->7) IS NULL OR (CASE WHEN
                jsonb_typeof(((("fleet_telemetry_row"."effects"->0)->'observations')->7)) = 'object' AND jsonb_typeof(((("fleet_telemetry_row"."effects"->0)->'observations')->7)->'origin_ms') = 'number' THEN
                ((("fleet_telemetry_row"."effects"->0)->'observations')->7) - 'name' - 'origin_ms' = '{}'::jsonb AND
                (((("fleet_telemetry_row"."effects"->0)->'observations')->7)->'name' = 'null'::jsonb OR (jsonb_typeof(((("fleet_telemetry_row"."effects"->0)->'observations')->7)->'name') = 'string' AND length(((("fleet_telemetry_row"."effects"->0)->'observations')->7)->>'name') BETWEEN 1 AND 64 AND octet_length(((("fleet_telemetry_row"."effects"->0)->'observations')->7)->>'name') <= 256)) AND
                (((("fleet_telemetry_row"."effects"->0)->'observations')->7)->>'origin_ms')::numeric = trunc((((("fleet_telemetry_row"."effects"->0)->'observations')->7)->>'origin_ms')::numeric) AND (((("fleet_telemetry_row"."effects"->0)->'observations')->7)->>'origin_ms')::numeric BETWEEN 0 AND "fleet_telemetry_row"."activity_origin_ms" AND
                "fleet_telemetry_row"."sampled_at_ms" - (((("fleet_telemetry_row"."effects"->0)->'observations')->7)->>'origin_ms')::numeric < 30000
                AND ((("fleet_telemetry_row"."effects"->0)->'observations')->7)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->0->'name' AND ((("fleet_telemetry_row"."effects"->0)->'observations')->7)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->1->'name' AND ((("fleet_telemetry_row"."effects"->0)->'observations')->7)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->2->'name' AND ((("fleet_telemetry_row"."effects"->0)->'observations')->7)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->3->'name' AND ((("fleet_telemetry_row"."effects"->0)->'observations')->7)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->4->'name' AND ((("fleet_telemetry_row"."effects"->0)->'observations')->7)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->5->'name' AND ((("fleet_telemetry_row"."effects"->0)->'observations')->7)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->6->'name'
                ELSE false END)) AND (((("fleet_telemetry_row"."effects"->0)->'observations')->8) IS NULL OR (CASE WHEN
                jsonb_typeof(((("fleet_telemetry_row"."effects"->0)->'observations')->8)) = 'object' AND jsonb_typeof(((("fleet_telemetry_row"."effects"->0)->'observations')->8)->'origin_ms') = 'number' THEN
                ((("fleet_telemetry_row"."effects"->0)->'observations')->8) - 'name' - 'origin_ms' = '{}'::jsonb AND
                (((("fleet_telemetry_row"."effects"->0)->'observations')->8)->'name' = 'null'::jsonb OR (jsonb_typeof(((("fleet_telemetry_row"."effects"->0)->'observations')->8)->'name') = 'string' AND length(((("fleet_telemetry_row"."effects"->0)->'observations')->8)->>'name') BETWEEN 1 AND 64 AND octet_length(((("fleet_telemetry_row"."effects"->0)->'observations')->8)->>'name') <= 256)) AND
                (((("fleet_telemetry_row"."effects"->0)->'observations')->8)->>'origin_ms')::numeric = trunc((((("fleet_telemetry_row"."effects"->0)->'observations')->8)->>'origin_ms')::numeric) AND (((("fleet_telemetry_row"."effects"->0)->'observations')->8)->>'origin_ms')::numeric BETWEEN 0 AND "fleet_telemetry_row"."activity_origin_ms" AND
                "fleet_telemetry_row"."sampled_at_ms" - (((("fleet_telemetry_row"."effects"->0)->'observations')->8)->>'origin_ms')::numeric < 30000
                AND ((("fleet_telemetry_row"."effects"->0)->'observations')->8)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->0->'name' AND ((("fleet_telemetry_row"."effects"->0)->'observations')->8)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->1->'name' AND ((("fleet_telemetry_row"."effects"->0)->'observations')->8)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->2->'name' AND ((("fleet_telemetry_row"."effects"->0)->'observations')->8)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->3->'name' AND ((("fleet_telemetry_row"."effects"->0)->'observations')->8)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->4->'name' AND ((("fleet_telemetry_row"."effects"->0)->'observations')->8)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->5->'name' AND ((("fleet_telemetry_row"."effects"->0)->'observations')->8)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->6->'name' AND ((("fleet_telemetry_row"."effects"->0)->'observations')->8)->'name' <> (("fleet_telemetry_row"."effects"->0)->'observations')->7->'name'
                ELSE false END))
            ELSE false END)) AND (("fleet_telemetry_row"."effects"->1) IS NULL OR (CASE WHEN
            jsonb_typeof(("fleet_telemetry_row"."effects"->1)) = 'object' AND
            jsonb_typeof((("fleet_telemetry_row"."effects"->1)->'observations')) = 'array' THEN
            ("fleet_telemetry_row"."effects"->1) - 'kind' - 'observations' = '{}'::jsonb AND
            ("fleet_telemetry_row"."effects"->1)->>'kind' IN ('SCRAM', 'POINT', 'NEUT') AND
            array_position(ARRAY['SCRAM','POINT','NEUT'], ("fleet_telemetry_row"."effects"->0->>'kind')) < array_position(ARRAY['SCRAM','POINT','NEUT'], ("fleet_telemetry_row"."effects"->1)->>'kind') AND
            jsonb_array_length((("fleet_telemetry_row"."effects"->1)->'observations')) BETWEEN 1 AND 9 AND
            jsonb_array_length(jsonb_path_query_array((("fleet_telemetry_row"."effects"->1)->'observations'), '$[*] ? (@.name != null)')) <= 8 AND
            (("fleet_telemetry_row"."effects"->1)->>'kind' <> 'NEUT' OR (jsonb_array_length((("fleet_telemetry_row"."effects"->1)->'observations')) = 1 AND (("fleet_telemetry_row"."effects"->1)->'observations')->0->'name' = 'null'::jsonb)) AND
            (((("fleet_telemetry_row"."effects"->1)->'observations')->0) IS NULL OR (CASE WHEN
                jsonb_typeof(((("fleet_telemetry_row"."effects"->1)->'observations')->0)) = 'object' AND jsonb_typeof(((("fleet_telemetry_row"."effects"->1)->'observations')->0)->'origin_ms') = 'number' THEN
                ((("fleet_telemetry_row"."effects"->1)->'observations')->0) - 'name' - 'origin_ms' = '{}'::jsonb AND
                (((("fleet_telemetry_row"."effects"->1)->'observations')->0)->'name' = 'null'::jsonb OR (jsonb_typeof(((("fleet_telemetry_row"."effects"->1)->'observations')->0)->'name') = 'string' AND length(((("fleet_telemetry_row"."effects"->1)->'observations')->0)->>'name') BETWEEN 1 AND 64 AND octet_length(((("fleet_telemetry_row"."effects"->1)->'observations')->0)->>'name') <= 256)) AND
                (((("fleet_telemetry_row"."effects"->1)->'observations')->0)->>'origin_ms')::numeric = trunc((((("fleet_telemetry_row"."effects"->1)->'observations')->0)->>'origin_ms')::numeric) AND (((("fleet_telemetry_row"."effects"->1)->'observations')->0)->>'origin_ms')::numeric BETWEEN 0 AND "fleet_telemetry_row"."activity_origin_ms" AND
                "fleet_telemetry_row"."sampled_at_ms" - (((("fleet_telemetry_row"."effects"->1)->'observations')->0)->>'origin_ms')::numeric < 30000
                
                ELSE false END)) AND (((("fleet_telemetry_row"."effects"->1)->'observations')->1) IS NULL OR (CASE WHEN
                jsonb_typeof(((("fleet_telemetry_row"."effects"->1)->'observations')->1)) = 'object' AND jsonb_typeof(((("fleet_telemetry_row"."effects"->1)->'observations')->1)->'origin_ms') = 'number' THEN
                ((("fleet_telemetry_row"."effects"->1)->'observations')->1) - 'name' - 'origin_ms' = '{}'::jsonb AND
                (((("fleet_telemetry_row"."effects"->1)->'observations')->1)->'name' = 'null'::jsonb OR (jsonb_typeof(((("fleet_telemetry_row"."effects"->1)->'observations')->1)->'name') = 'string' AND length(((("fleet_telemetry_row"."effects"->1)->'observations')->1)->>'name') BETWEEN 1 AND 64 AND octet_length(((("fleet_telemetry_row"."effects"->1)->'observations')->1)->>'name') <= 256)) AND
                (((("fleet_telemetry_row"."effects"->1)->'observations')->1)->>'origin_ms')::numeric = trunc((((("fleet_telemetry_row"."effects"->1)->'observations')->1)->>'origin_ms')::numeric) AND (((("fleet_telemetry_row"."effects"->1)->'observations')->1)->>'origin_ms')::numeric BETWEEN 0 AND "fleet_telemetry_row"."activity_origin_ms" AND
                "fleet_telemetry_row"."sampled_at_ms" - (((("fleet_telemetry_row"."effects"->1)->'observations')->1)->>'origin_ms')::numeric < 30000
                AND ((("fleet_telemetry_row"."effects"->1)->'observations')->1)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->0->'name'
                ELSE false END)) AND (((("fleet_telemetry_row"."effects"->1)->'observations')->2) IS NULL OR (CASE WHEN
                jsonb_typeof(((("fleet_telemetry_row"."effects"->1)->'observations')->2)) = 'object' AND jsonb_typeof(((("fleet_telemetry_row"."effects"->1)->'observations')->2)->'origin_ms') = 'number' THEN
                ((("fleet_telemetry_row"."effects"->1)->'observations')->2) - 'name' - 'origin_ms' = '{}'::jsonb AND
                (((("fleet_telemetry_row"."effects"->1)->'observations')->2)->'name' = 'null'::jsonb OR (jsonb_typeof(((("fleet_telemetry_row"."effects"->1)->'observations')->2)->'name') = 'string' AND length(((("fleet_telemetry_row"."effects"->1)->'observations')->2)->>'name') BETWEEN 1 AND 64 AND octet_length(((("fleet_telemetry_row"."effects"->1)->'observations')->2)->>'name') <= 256)) AND
                (((("fleet_telemetry_row"."effects"->1)->'observations')->2)->>'origin_ms')::numeric = trunc((((("fleet_telemetry_row"."effects"->1)->'observations')->2)->>'origin_ms')::numeric) AND (((("fleet_telemetry_row"."effects"->1)->'observations')->2)->>'origin_ms')::numeric BETWEEN 0 AND "fleet_telemetry_row"."activity_origin_ms" AND
                "fleet_telemetry_row"."sampled_at_ms" - (((("fleet_telemetry_row"."effects"->1)->'observations')->2)->>'origin_ms')::numeric < 30000
                AND ((("fleet_telemetry_row"."effects"->1)->'observations')->2)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->0->'name' AND ((("fleet_telemetry_row"."effects"->1)->'observations')->2)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->1->'name'
                ELSE false END)) AND (((("fleet_telemetry_row"."effects"->1)->'observations')->3) IS NULL OR (CASE WHEN
                jsonb_typeof(((("fleet_telemetry_row"."effects"->1)->'observations')->3)) = 'object' AND jsonb_typeof(((("fleet_telemetry_row"."effects"->1)->'observations')->3)->'origin_ms') = 'number' THEN
                ((("fleet_telemetry_row"."effects"->1)->'observations')->3) - 'name' - 'origin_ms' = '{}'::jsonb AND
                (((("fleet_telemetry_row"."effects"->1)->'observations')->3)->'name' = 'null'::jsonb OR (jsonb_typeof(((("fleet_telemetry_row"."effects"->1)->'observations')->3)->'name') = 'string' AND length(((("fleet_telemetry_row"."effects"->1)->'observations')->3)->>'name') BETWEEN 1 AND 64 AND octet_length(((("fleet_telemetry_row"."effects"->1)->'observations')->3)->>'name') <= 256)) AND
                (((("fleet_telemetry_row"."effects"->1)->'observations')->3)->>'origin_ms')::numeric = trunc((((("fleet_telemetry_row"."effects"->1)->'observations')->3)->>'origin_ms')::numeric) AND (((("fleet_telemetry_row"."effects"->1)->'observations')->3)->>'origin_ms')::numeric BETWEEN 0 AND "fleet_telemetry_row"."activity_origin_ms" AND
                "fleet_telemetry_row"."sampled_at_ms" - (((("fleet_telemetry_row"."effects"->1)->'observations')->3)->>'origin_ms')::numeric < 30000
                AND ((("fleet_telemetry_row"."effects"->1)->'observations')->3)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->0->'name' AND ((("fleet_telemetry_row"."effects"->1)->'observations')->3)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->1->'name' AND ((("fleet_telemetry_row"."effects"->1)->'observations')->3)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->2->'name'
                ELSE false END)) AND (((("fleet_telemetry_row"."effects"->1)->'observations')->4) IS NULL OR (CASE WHEN
                jsonb_typeof(((("fleet_telemetry_row"."effects"->1)->'observations')->4)) = 'object' AND jsonb_typeof(((("fleet_telemetry_row"."effects"->1)->'observations')->4)->'origin_ms') = 'number' THEN
                ((("fleet_telemetry_row"."effects"->1)->'observations')->4) - 'name' - 'origin_ms' = '{}'::jsonb AND
                (((("fleet_telemetry_row"."effects"->1)->'observations')->4)->'name' = 'null'::jsonb OR (jsonb_typeof(((("fleet_telemetry_row"."effects"->1)->'observations')->4)->'name') = 'string' AND length(((("fleet_telemetry_row"."effects"->1)->'observations')->4)->>'name') BETWEEN 1 AND 64 AND octet_length(((("fleet_telemetry_row"."effects"->1)->'observations')->4)->>'name') <= 256)) AND
                (((("fleet_telemetry_row"."effects"->1)->'observations')->4)->>'origin_ms')::numeric = trunc((((("fleet_telemetry_row"."effects"->1)->'observations')->4)->>'origin_ms')::numeric) AND (((("fleet_telemetry_row"."effects"->1)->'observations')->4)->>'origin_ms')::numeric BETWEEN 0 AND "fleet_telemetry_row"."activity_origin_ms" AND
                "fleet_telemetry_row"."sampled_at_ms" - (((("fleet_telemetry_row"."effects"->1)->'observations')->4)->>'origin_ms')::numeric < 30000
                AND ((("fleet_telemetry_row"."effects"->1)->'observations')->4)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->0->'name' AND ((("fleet_telemetry_row"."effects"->1)->'observations')->4)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->1->'name' AND ((("fleet_telemetry_row"."effects"->1)->'observations')->4)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->2->'name' AND ((("fleet_telemetry_row"."effects"->1)->'observations')->4)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->3->'name'
                ELSE false END)) AND (((("fleet_telemetry_row"."effects"->1)->'observations')->5) IS NULL OR (CASE WHEN
                jsonb_typeof(((("fleet_telemetry_row"."effects"->1)->'observations')->5)) = 'object' AND jsonb_typeof(((("fleet_telemetry_row"."effects"->1)->'observations')->5)->'origin_ms') = 'number' THEN
                ((("fleet_telemetry_row"."effects"->1)->'observations')->5) - 'name' - 'origin_ms' = '{}'::jsonb AND
                (((("fleet_telemetry_row"."effects"->1)->'observations')->5)->'name' = 'null'::jsonb OR (jsonb_typeof(((("fleet_telemetry_row"."effects"->1)->'observations')->5)->'name') = 'string' AND length(((("fleet_telemetry_row"."effects"->1)->'observations')->5)->>'name') BETWEEN 1 AND 64 AND octet_length(((("fleet_telemetry_row"."effects"->1)->'observations')->5)->>'name') <= 256)) AND
                (((("fleet_telemetry_row"."effects"->1)->'observations')->5)->>'origin_ms')::numeric = trunc((((("fleet_telemetry_row"."effects"->1)->'observations')->5)->>'origin_ms')::numeric) AND (((("fleet_telemetry_row"."effects"->1)->'observations')->5)->>'origin_ms')::numeric BETWEEN 0 AND "fleet_telemetry_row"."activity_origin_ms" AND
                "fleet_telemetry_row"."sampled_at_ms" - (((("fleet_telemetry_row"."effects"->1)->'observations')->5)->>'origin_ms')::numeric < 30000
                AND ((("fleet_telemetry_row"."effects"->1)->'observations')->5)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->0->'name' AND ((("fleet_telemetry_row"."effects"->1)->'observations')->5)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->1->'name' AND ((("fleet_telemetry_row"."effects"->1)->'observations')->5)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->2->'name' AND ((("fleet_telemetry_row"."effects"->1)->'observations')->5)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->3->'name' AND ((("fleet_telemetry_row"."effects"->1)->'observations')->5)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->4->'name'
                ELSE false END)) AND (((("fleet_telemetry_row"."effects"->1)->'observations')->6) IS NULL OR (CASE WHEN
                jsonb_typeof(((("fleet_telemetry_row"."effects"->1)->'observations')->6)) = 'object' AND jsonb_typeof(((("fleet_telemetry_row"."effects"->1)->'observations')->6)->'origin_ms') = 'number' THEN
                ((("fleet_telemetry_row"."effects"->1)->'observations')->6) - 'name' - 'origin_ms' = '{}'::jsonb AND
                (((("fleet_telemetry_row"."effects"->1)->'observations')->6)->'name' = 'null'::jsonb OR (jsonb_typeof(((("fleet_telemetry_row"."effects"->1)->'observations')->6)->'name') = 'string' AND length(((("fleet_telemetry_row"."effects"->1)->'observations')->6)->>'name') BETWEEN 1 AND 64 AND octet_length(((("fleet_telemetry_row"."effects"->1)->'observations')->6)->>'name') <= 256)) AND
                (((("fleet_telemetry_row"."effects"->1)->'observations')->6)->>'origin_ms')::numeric = trunc((((("fleet_telemetry_row"."effects"->1)->'observations')->6)->>'origin_ms')::numeric) AND (((("fleet_telemetry_row"."effects"->1)->'observations')->6)->>'origin_ms')::numeric BETWEEN 0 AND "fleet_telemetry_row"."activity_origin_ms" AND
                "fleet_telemetry_row"."sampled_at_ms" - (((("fleet_telemetry_row"."effects"->1)->'observations')->6)->>'origin_ms')::numeric < 30000
                AND ((("fleet_telemetry_row"."effects"->1)->'observations')->6)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->0->'name' AND ((("fleet_telemetry_row"."effects"->1)->'observations')->6)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->1->'name' AND ((("fleet_telemetry_row"."effects"->1)->'observations')->6)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->2->'name' AND ((("fleet_telemetry_row"."effects"->1)->'observations')->6)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->3->'name' AND ((("fleet_telemetry_row"."effects"->1)->'observations')->6)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->4->'name' AND ((("fleet_telemetry_row"."effects"->1)->'observations')->6)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->5->'name'
                ELSE false END)) AND (((("fleet_telemetry_row"."effects"->1)->'observations')->7) IS NULL OR (CASE WHEN
                jsonb_typeof(((("fleet_telemetry_row"."effects"->1)->'observations')->7)) = 'object' AND jsonb_typeof(((("fleet_telemetry_row"."effects"->1)->'observations')->7)->'origin_ms') = 'number' THEN
                ((("fleet_telemetry_row"."effects"->1)->'observations')->7) - 'name' - 'origin_ms' = '{}'::jsonb AND
                (((("fleet_telemetry_row"."effects"->1)->'observations')->7)->'name' = 'null'::jsonb OR (jsonb_typeof(((("fleet_telemetry_row"."effects"->1)->'observations')->7)->'name') = 'string' AND length(((("fleet_telemetry_row"."effects"->1)->'observations')->7)->>'name') BETWEEN 1 AND 64 AND octet_length(((("fleet_telemetry_row"."effects"->1)->'observations')->7)->>'name') <= 256)) AND
                (((("fleet_telemetry_row"."effects"->1)->'observations')->7)->>'origin_ms')::numeric = trunc((((("fleet_telemetry_row"."effects"->1)->'observations')->7)->>'origin_ms')::numeric) AND (((("fleet_telemetry_row"."effects"->1)->'observations')->7)->>'origin_ms')::numeric BETWEEN 0 AND "fleet_telemetry_row"."activity_origin_ms" AND
                "fleet_telemetry_row"."sampled_at_ms" - (((("fleet_telemetry_row"."effects"->1)->'observations')->7)->>'origin_ms')::numeric < 30000
                AND ((("fleet_telemetry_row"."effects"->1)->'observations')->7)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->0->'name' AND ((("fleet_telemetry_row"."effects"->1)->'observations')->7)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->1->'name' AND ((("fleet_telemetry_row"."effects"->1)->'observations')->7)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->2->'name' AND ((("fleet_telemetry_row"."effects"->1)->'observations')->7)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->3->'name' AND ((("fleet_telemetry_row"."effects"->1)->'observations')->7)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->4->'name' AND ((("fleet_telemetry_row"."effects"->1)->'observations')->7)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->5->'name' AND ((("fleet_telemetry_row"."effects"->1)->'observations')->7)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->6->'name'
                ELSE false END)) AND (((("fleet_telemetry_row"."effects"->1)->'observations')->8) IS NULL OR (CASE WHEN
                jsonb_typeof(((("fleet_telemetry_row"."effects"->1)->'observations')->8)) = 'object' AND jsonb_typeof(((("fleet_telemetry_row"."effects"->1)->'observations')->8)->'origin_ms') = 'number' THEN
                ((("fleet_telemetry_row"."effects"->1)->'observations')->8) - 'name' - 'origin_ms' = '{}'::jsonb AND
                (((("fleet_telemetry_row"."effects"->1)->'observations')->8)->'name' = 'null'::jsonb OR (jsonb_typeof(((("fleet_telemetry_row"."effects"->1)->'observations')->8)->'name') = 'string' AND length(((("fleet_telemetry_row"."effects"->1)->'observations')->8)->>'name') BETWEEN 1 AND 64 AND octet_length(((("fleet_telemetry_row"."effects"->1)->'observations')->8)->>'name') <= 256)) AND
                (((("fleet_telemetry_row"."effects"->1)->'observations')->8)->>'origin_ms')::numeric = trunc((((("fleet_telemetry_row"."effects"->1)->'observations')->8)->>'origin_ms')::numeric) AND (((("fleet_telemetry_row"."effects"->1)->'observations')->8)->>'origin_ms')::numeric BETWEEN 0 AND "fleet_telemetry_row"."activity_origin_ms" AND
                "fleet_telemetry_row"."sampled_at_ms" - (((("fleet_telemetry_row"."effects"->1)->'observations')->8)->>'origin_ms')::numeric < 30000
                AND ((("fleet_telemetry_row"."effects"->1)->'observations')->8)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->0->'name' AND ((("fleet_telemetry_row"."effects"->1)->'observations')->8)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->1->'name' AND ((("fleet_telemetry_row"."effects"->1)->'observations')->8)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->2->'name' AND ((("fleet_telemetry_row"."effects"->1)->'observations')->8)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->3->'name' AND ((("fleet_telemetry_row"."effects"->1)->'observations')->8)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->4->'name' AND ((("fleet_telemetry_row"."effects"->1)->'observations')->8)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->5->'name' AND ((("fleet_telemetry_row"."effects"->1)->'observations')->8)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->6->'name' AND ((("fleet_telemetry_row"."effects"->1)->'observations')->8)->'name' <> (("fleet_telemetry_row"."effects"->1)->'observations')->7->'name'
                ELSE false END))
            ELSE false END)) AND (("fleet_telemetry_row"."effects"->2) IS NULL OR (CASE WHEN
            jsonb_typeof(("fleet_telemetry_row"."effects"->2)) = 'object' AND
            jsonb_typeof((("fleet_telemetry_row"."effects"->2)->'observations')) = 'array' THEN
            ("fleet_telemetry_row"."effects"->2) - 'kind' - 'observations' = '{}'::jsonb AND
            ("fleet_telemetry_row"."effects"->2)->>'kind' IN ('SCRAM', 'POINT', 'NEUT') AND
            array_position(ARRAY['SCRAM','POINT','NEUT'], ("fleet_telemetry_row"."effects"->1->>'kind')) < array_position(ARRAY['SCRAM','POINT','NEUT'], ("fleet_telemetry_row"."effects"->2)->>'kind') AND
            jsonb_array_length((("fleet_telemetry_row"."effects"->2)->'observations')) BETWEEN 1 AND 9 AND
            jsonb_array_length(jsonb_path_query_array((("fleet_telemetry_row"."effects"->2)->'observations'), '$[*] ? (@.name != null)')) <= 8 AND
            (("fleet_telemetry_row"."effects"->2)->>'kind' <> 'NEUT' OR (jsonb_array_length((("fleet_telemetry_row"."effects"->2)->'observations')) = 1 AND (("fleet_telemetry_row"."effects"->2)->'observations')->0->'name' = 'null'::jsonb)) AND
            (((("fleet_telemetry_row"."effects"->2)->'observations')->0) IS NULL OR (CASE WHEN
                jsonb_typeof(((("fleet_telemetry_row"."effects"->2)->'observations')->0)) = 'object' AND jsonb_typeof(((("fleet_telemetry_row"."effects"->2)->'observations')->0)->'origin_ms') = 'number' THEN
                ((("fleet_telemetry_row"."effects"->2)->'observations')->0) - 'name' - 'origin_ms' = '{}'::jsonb AND
                (((("fleet_telemetry_row"."effects"->2)->'observations')->0)->'name' = 'null'::jsonb OR (jsonb_typeof(((("fleet_telemetry_row"."effects"->2)->'observations')->0)->'name') = 'string' AND length(((("fleet_telemetry_row"."effects"->2)->'observations')->0)->>'name') BETWEEN 1 AND 64 AND octet_length(((("fleet_telemetry_row"."effects"->2)->'observations')->0)->>'name') <= 256)) AND
                (((("fleet_telemetry_row"."effects"->2)->'observations')->0)->>'origin_ms')::numeric = trunc((((("fleet_telemetry_row"."effects"->2)->'observations')->0)->>'origin_ms')::numeric) AND (((("fleet_telemetry_row"."effects"->2)->'observations')->0)->>'origin_ms')::numeric BETWEEN 0 AND "fleet_telemetry_row"."activity_origin_ms" AND
                "fleet_telemetry_row"."sampled_at_ms" - (((("fleet_telemetry_row"."effects"->2)->'observations')->0)->>'origin_ms')::numeric < 30000
                
                ELSE false END)) AND (((("fleet_telemetry_row"."effects"->2)->'observations')->1) IS NULL OR (CASE WHEN
                jsonb_typeof(((("fleet_telemetry_row"."effects"->2)->'observations')->1)) = 'object' AND jsonb_typeof(((("fleet_telemetry_row"."effects"->2)->'observations')->1)->'origin_ms') = 'number' THEN
                ((("fleet_telemetry_row"."effects"->2)->'observations')->1) - 'name' - 'origin_ms' = '{}'::jsonb AND
                (((("fleet_telemetry_row"."effects"->2)->'observations')->1)->'name' = 'null'::jsonb OR (jsonb_typeof(((("fleet_telemetry_row"."effects"->2)->'observations')->1)->'name') = 'string' AND length(((("fleet_telemetry_row"."effects"->2)->'observations')->1)->>'name') BETWEEN 1 AND 64 AND octet_length(((("fleet_telemetry_row"."effects"->2)->'observations')->1)->>'name') <= 256)) AND
                (((("fleet_telemetry_row"."effects"->2)->'observations')->1)->>'origin_ms')::numeric = trunc((((("fleet_telemetry_row"."effects"->2)->'observations')->1)->>'origin_ms')::numeric) AND (((("fleet_telemetry_row"."effects"->2)->'observations')->1)->>'origin_ms')::numeric BETWEEN 0 AND "fleet_telemetry_row"."activity_origin_ms" AND
                "fleet_telemetry_row"."sampled_at_ms" - (((("fleet_telemetry_row"."effects"->2)->'observations')->1)->>'origin_ms')::numeric < 30000
                AND ((("fleet_telemetry_row"."effects"->2)->'observations')->1)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->0->'name'
                ELSE false END)) AND (((("fleet_telemetry_row"."effects"->2)->'observations')->2) IS NULL OR (CASE WHEN
                jsonb_typeof(((("fleet_telemetry_row"."effects"->2)->'observations')->2)) = 'object' AND jsonb_typeof(((("fleet_telemetry_row"."effects"->2)->'observations')->2)->'origin_ms') = 'number' THEN
                ((("fleet_telemetry_row"."effects"->2)->'observations')->2) - 'name' - 'origin_ms' = '{}'::jsonb AND
                (((("fleet_telemetry_row"."effects"->2)->'observations')->2)->'name' = 'null'::jsonb OR (jsonb_typeof(((("fleet_telemetry_row"."effects"->2)->'observations')->2)->'name') = 'string' AND length(((("fleet_telemetry_row"."effects"->2)->'observations')->2)->>'name') BETWEEN 1 AND 64 AND octet_length(((("fleet_telemetry_row"."effects"->2)->'observations')->2)->>'name') <= 256)) AND
                (((("fleet_telemetry_row"."effects"->2)->'observations')->2)->>'origin_ms')::numeric = trunc((((("fleet_telemetry_row"."effects"->2)->'observations')->2)->>'origin_ms')::numeric) AND (((("fleet_telemetry_row"."effects"->2)->'observations')->2)->>'origin_ms')::numeric BETWEEN 0 AND "fleet_telemetry_row"."activity_origin_ms" AND
                "fleet_telemetry_row"."sampled_at_ms" - (((("fleet_telemetry_row"."effects"->2)->'observations')->2)->>'origin_ms')::numeric < 30000
                AND ((("fleet_telemetry_row"."effects"->2)->'observations')->2)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->0->'name' AND ((("fleet_telemetry_row"."effects"->2)->'observations')->2)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->1->'name'
                ELSE false END)) AND (((("fleet_telemetry_row"."effects"->2)->'observations')->3) IS NULL OR (CASE WHEN
                jsonb_typeof(((("fleet_telemetry_row"."effects"->2)->'observations')->3)) = 'object' AND jsonb_typeof(((("fleet_telemetry_row"."effects"->2)->'observations')->3)->'origin_ms') = 'number' THEN
                ((("fleet_telemetry_row"."effects"->2)->'observations')->3) - 'name' - 'origin_ms' = '{}'::jsonb AND
                (((("fleet_telemetry_row"."effects"->2)->'observations')->3)->'name' = 'null'::jsonb OR (jsonb_typeof(((("fleet_telemetry_row"."effects"->2)->'observations')->3)->'name') = 'string' AND length(((("fleet_telemetry_row"."effects"->2)->'observations')->3)->>'name') BETWEEN 1 AND 64 AND octet_length(((("fleet_telemetry_row"."effects"->2)->'observations')->3)->>'name') <= 256)) AND
                (((("fleet_telemetry_row"."effects"->2)->'observations')->3)->>'origin_ms')::numeric = trunc((((("fleet_telemetry_row"."effects"->2)->'observations')->3)->>'origin_ms')::numeric) AND (((("fleet_telemetry_row"."effects"->2)->'observations')->3)->>'origin_ms')::numeric BETWEEN 0 AND "fleet_telemetry_row"."activity_origin_ms" AND
                "fleet_telemetry_row"."sampled_at_ms" - (((("fleet_telemetry_row"."effects"->2)->'observations')->3)->>'origin_ms')::numeric < 30000
                AND ((("fleet_telemetry_row"."effects"->2)->'observations')->3)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->0->'name' AND ((("fleet_telemetry_row"."effects"->2)->'observations')->3)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->1->'name' AND ((("fleet_telemetry_row"."effects"->2)->'observations')->3)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->2->'name'
                ELSE false END)) AND (((("fleet_telemetry_row"."effects"->2)->'observations')->4) IS NULL OR (CASE WHEN
                jsonb_typeof(((("fleet_telemetry_row"."effects"->2)->'observations')->4)) = 'object' AND jsonb_typeof(((("fleet_telemetry_row"."effects"->2)->'observations')->4)->'origin_ms') = 'number' THEN
                ((("fleet_telemetry_row"."effects"->2)->'observations')->4) - 'name' - 'origin_ms' = '{}'::jsonb AND
                (((("fleet_telemetry_row"."effects"->2)->'observations')->4)->'name' = 'null'::jsonb OR (jsonb_typeof(((("fleet_telemetry_row"."effects"->2)->'observations')->4)->'name') = 'string' AND length(((("fleet_telemetry_row"."effects"->2)->'observations')->4)->>'name') BETWEEN 1 AND 64 AND octet_length(((("fleet_telemetry_row"."effects"->2)->'observations')->4)->>'name') <= 256)) AND
                (((("fleet_telemetry_row"."effects"->2)->'observations')->4)->>'origin_ms')::numeric = trunc((((("fleet_telemetry_row"."effects"->2)->'observations')->4)->>'origin_ms')::numeric) AND (((("fleet_telemetry_row"."effects"->2)->'observations')->4)->>'origin_ms')::numeric BETWEEN 0 AND "fleet_telemetry_row"."activity_origin_ms" AND
                "fleet_telemetry_row"."sampled_at_ms" - (((("fleet_telemetry_row"."effects"->2)->'observations')->4)->>'origin_ms')::numeric < 30000
                AND ((("fleet_telemetry_row"."effects"->2)->'observations')->4)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->0->'name' AND ((("fleet_telemetry_row"."effects"->2)->'observations')->4)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->1->'name' AND ((("fleet_telemetry_row"."effects"->2)->'observations')->4)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->2->'name' AND ((("fleet_telemetry_row"."effects"->2)->'observations')->4)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->3->'name'
                ELSE false END)) AND (((("fleet_telemetry_row"."effects"->2)->'observations')->5) IS NULL OR (CASE WHEN
                jsonb_typeof(((("fleet_telemetry_row"."effects"->2)->'observations')->5)) = 'object' AND jsonb_typeof(((("fleet_telemetry_row"."effects"->2)->'observations')->5)->'origin_ms') = 'number' THEN
                ((("fleet_telemetry_row"."effects"->2)->'observations')->5) - 'name' - 'origin_ms' = '{}'::jsonb AND
                (((("fleet_telemetry_row"."effects"->2)->'observations')->5)->'name' = 'null'::jsonb OR (jsonb_typeof(((("fleet_telemetry_row"."effects"->2)->'observations')->5)->'name') = 'string' AND length(((("fleet_telemetry_row"."effects"->2)->'observations')->5)->>'name') BETWEEN 1 AND 64 AND octet_length(((("fleet_telemetry_row"."effects"->2)->'observations')->5)->>'name') <= 256)) AND
                (((("fleet_telemetry_row"."effects"->2)->'observations')->5)->>'origin_ms')::numeric = trunc((((("fleet_telemetry_row"."effects"->2)->'observations')->5)->>'origin_ms')::numeric) AND (((("fleet_telemetry_row"."effects"->2)->'observations')->5)->>'origin_ms')::numeric BETWEEN 0 AND "fleet_telemetry_row"."activity_origin_ms" AND
                "fleet_telemetry_row"."sampled_at_ms" - (((("fleet_telemetry_row"."effects"->2)->'observations')->5)->>'origin_ms')::numeric < 30000
                AND ((("fleet_telemetry_row"."effects"->2)->'observations')->5)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->0->'name' AND ((("fleet_telemetry_row"."effects"->2)->'observations')->5)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->1->'name' AND ((("fleet_telemetry_row"."effects"->2)->'observations')->5)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->2->'name' AND ((("fleet_telemetry_row"."effects"->2)->'observations')->5)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->3->'name' AND ((("fleet_telemetry_row"."effects"->2)->'observations')->5)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->4->'name'
                ELSE false END)) AND (((("fleet_telemetry_row"."effects"->2)->'observations')->6) IS NULL OR (CASE WHEN
                jsonb_typeof(((("fleet_telemetry_row"."effects"->2)->'observations')->6)) = 'object' AND jsonb_typeof(((("fleet_telemetry_row"."effects"->2)->'observations')->6)->'origin_ms') = 'number' THEN
                ((("fleet_telemetry_row"."effects"->2)->'observations')->6) - 'name' - 'origin_ms' = '{}'::jsonb AND
                (((("fleet_telemetry_row"."effects"->2)->'observations')->6)->'name' = 'null'::jsonb OR (jsonb_typeof(((("fleet_telemetry_row"."effects"->2)->'observations')->6)->'name') = 'string' AND length(((("fleet_telemetry_row"."effects"->2)->'observations')->6)->>'name') BETWEEN 1 AND 64 AND octet_length(((("fleet_telemetry_row"."effects"->2)->'observations')->6)->>'name') <= 256)) AND
                (((("fleet_telemetry_row"."effects"->2)->'observations')->6)->>'origin_ms')::numeric = trunc((((("fleet_telemetry_row"."effects"->2)->'observations')->6)->>'origin_ms')::numeric) AND (((("fleet_telemetry_row"."effects"->2)->'observations')->6)->>'origin_ms')::numeric BETWEEN 0 AND "fleet_telemetry_row"."activity_origin_ms" AND
                "fleet_telemetry_row"."sampled_at_ms" - (((("fleet_telemetry_row"."effects"->2)->'observations')->6)->>'origin_ms')::numeric < 30000
                AND ((("fleet_telemetry_row"."effects"->2)->'observations')->6)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->0->'name' AND ((("fleet_telemetry_row"."effects"->2)->'observations')->6)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->1->'name' AND ((("fleet_telemetry_row"."effects"->2)->'observations')->6)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->2->'name' AND ((("fleet_telemetry_row"."effects"->2)->'observations')->6)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->3->'name' AND ((("fleet_telemetry_row"."effects"->2)->'observations')->6)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->4->'name' AND ((("fleet_telemetry_row"."effects"->2)->'observations')->6)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->5->'name'
                ELSE false END)) AND (((("fleet_telemetry_row"."effects"->2)->'observations')->7) IS NULL OR (CASE WHEN
                jsonb_typeof(((("fleet_telemetry_row"."effects"->2)->'observations')->7)) = 'object' AND jsonb_typeof(((("fleet_telemetry_row"."effects"->2)->'observations')->7)->'origin_ms') = 'number' THEN
                ((("fleet_telemetry_row"."effects"->2)->'observations')->7) - 'name' - 'origin_ms' = '{}'::jsonb AND
                (((("fleet_telemetry_row"."effects"->2)->'observations')->7)->'name' = 'null'::jsonb OR (jsonb_typeof(((("fleet_telemetry_row"."effects"->2)->'observations')->7)->'name') = 'string' AND length(((("fleet_telemetry_row"."effects"->2)->'observations')->7)->>'name') BETWEEN 1 AND 64 AND octet_length(((("fleet_telemetry_row"."effects"->2)->'observations')->7)->>'name') <= 256)) AND
                (((("fleet_telemetry_row"."effects"->2)->'observations')->7)->>'origin_ms')::numeric = trunc((((("fleet_telemetry_row"."effects"->2)->'observations')->7)->>'origin_ms')::numeric) AND (((("fleet_telemetry_row"."effects"->2)->'observations')->7)->>'origin_ms')::numeric BETWEEN 0 AND "fleet_telemetry_row"."activity_origin_ms" AND
                "fleet_telemetry_row"."sampled_at_ms" - (((("fleet_telemetry_row"."effects"->2)->'observations')->7)->>'origin_ms')::numeric < 30000
                AND ((("fleet_telemetry_row"."effects"->2)->'observations')->7)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->0->'name' AND ((("fleet_telemetry_row"."effects"->2)->'observations')->7)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->1->'name' AND ((("fleet_telemetry_row"."effects"->2)->'observations')->7)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->2->'name' AND ((("fleet_telemetry_row"."effects"->2)->'observations')->7)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->3->'name' AND ((("fleet_telemetry_row"."effects"->2)->'observations')->7)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->4->'name' AND ((("fleet_telemetry_row"."effects"->2)->'observations')->7)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->5->'name' AND ((("fleet_telemetry_row"."effects"->2)->'observations')->7)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->6->'name'
                ELSE false END)) AND (((("fleet_telemetry_row"."effects"->2)->'observations')->8) IS NULL OR (CASE WHEN
                jsonb_typeof(((("fleet_telemetry_row"."effects"->2)->'observations')->8)) = 'object' AND jsonb_typeof(((("fleet_telemetry_row"."effects"->2)->'observations')->8)->'origin_ms') = 'number' THEN
                ((("fleet_telemetry_row"."effects"->2)->'observations')->8) - 'name' - 'origin_ms' = '{}'::jsonb AND
                (((("fleet_telemetry_row"."effects"->2)->'observations')->8)->'name' = 'null'::jsonb OR (jsonb_typeof(((("fleet_telemetry_row"."effects"->2)->'observations')->8)->'name') = 'string' AND length(((("fleet_telemetry_row"."effects"->2)->'observations')->8)->>'name') BETWEEN 1 AND 64 AND octet_length(((("fleet_telemetry_row"."effects"->2)->'observations')->8)->>'name') <= 256)) AND
                (((("fleet_telemetry_row"."effects"->2)->'observations')->8)->>'origin_ms')::numeric = trunc((((("fleet_telemetry_row"."effects"->2)->'observations')->8)->>'origin_ms')::numeric) AND (((("fleet_telemetry_row"."effects"->2)->'observations')->8)->>'origin_ms')::numeric BETWEEN 0 AND "fleet_telemetry_row"."activity_origin_ms" AND
                "fleet_telemetry_row"."sampled_at_ms" - (((("fleet_telemetry_row"."effects"->2)->'observations')->8)->>'origin_ms')::numeric < 30000
                AND ((("fleet_telemetry_row"."effects"->2)->'observations')->8)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->0->'name' AND ((("fleet_telemetry_row"."effects"->2)->'observations')->8)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->1->'name' AND ((("fleet_telemetry_row"."effects"->2)->'observations')->8)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->2->'name' AND ((("fleet_telemetry_row"."effects"->2)->'observations')->8)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->3->'name' AND ((("fleet_telemetry_row"."effects"->2)->'observations')->8)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->4->'name' AND ((("fleet_telemetry_row"."effects"->2)->'observations')->8)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->5->'name' AND ((("fleet_telemetry_row"."effects"->2)->'observations')->8)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->6->'name' AND ((("fleet_telemetry_row"."effects"->2)->'observations')->8)->'name' <> (("fleet_telemetry_row"."effects"->2)->'observations')->7->'name'
                ELSE false END))
            ELSE false END))
      ELSE false END) IS TRUE);