ALTER TABLE "fleet_automatic_receipt" DROP CONSTRAINT "fleet_automatic_receipt_payload_ck";--> statement-breakpoint
ALTER TABLE "fleet_source_intent" DROP CONSTRAINT "fleet_source_intent_stop_receipt_ck";--> statement-breakpoint
ALTER TABLE "fleet_automatic_receipt" ADD CONSTRAINT "fleet_automatic_receipt_payload_ck" CHECK ((CASE WHEN octet_length("fleet_automatic_receipt"."receipt"::text) <= 2048 AND
    (jsonb_typeof("fleet_automatic_receipt"."receipt") = 'object' AND "fleet_automatic_receipt"."receipt" ?& ARRAY['kind', 'command', 'accepted_at', 'expires_at', 'result']::text[] AND "fleet_automatic_receipt"."receipt" - ARRAY['kind', 'command', 'accepted_at', 'expires_at', 'result']::text[] = '{}'::jsonb) AND ("fleet_automatic_receipt"."receipt"->'kind') = '"automatic"'::jsonb AND
    (((jsonb_typeof(("fleet_automatic_receipt"."receipt"->'command')) = 'object' AND ("fleet_automatic_receipt"."receipt"->'command') ?& ARRAY['protocol', 'request_id', 'intent_created_at', 'enabled', 'expected_generation', 'expected_revision']::text[] AND ("fleet_automatic_receipt"."receipt"->'command') - ARRAY['protocol', 'request_id', 'intent_created_at', 'enabled', 'expected_generation', 'expected_revision']::text[] = '{}'::jsonb) AND (("fleet_automatic_receipt"."receipt"->'command')->'protocol') = '2'::jsonb AND (jsonb_typeof((("fleet_automatic_receipt"."receipt"->'command')->'request_id')) = 'string' AND ((("fleet_automatic_receipt"."receipt"->'command')->'request_id') #>> '{}') ~ '^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$') AND (CASE WHEN jsonb_typeof((("fleet_automatic_receipt"."receipt"->'command')->'intent_created_at')) = 'string' AND ((("fleet_automatic_receipt"."receipt"->'command')->'intent_created_at') #>> '{}') ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}[.][0-9]{3}Z$' AND left(((("fleet_automatic_receipt"."receipt"->'command')->'intent_created_at') #>> '{}'), 4) <> '0000'
    THEN to_char(((("fleet_automatic_receipt"."receipt"->'command')->'intent_created_at') #>> '{}')::timestamptz AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') = ((("fleet_automatic_receipt"."receipt"->'command')->'intent_created_at') #>> '{}') ELSE false END) AND
    (CASE WHEN jsonb_typeof((("fleet_automatic_receipt"."receipt"->'command')->'expected_generation')) = 'number' THEN ((("fleet_automatic_receipt"."receipt"->'command')->'expected_generation') #>> '{}')::numeric = trunc(((("fleet_automatic_receipt"."receipt"->'command')->'expected_generation') #>> '{}')::numeric) AND ((("fleet_automatic_receipt"."receipt"->'command')->'expected_generation') #>> '{}')::numeric BETWEEN 0 AND 9007199254740991 ELSE false END) AND
    jsonb_typeof((("fleet_automatic_receipt"."receipt"->'command')->'enabled')) = 'boolean' AND (CASE WHEN jsonb_typeof((("fleet_automatic_receipt"."receipt"->'command')->'expected_revision')) = 'number' THEN ((("fleet_automatic_receipt"."receipt"->'command')->'expected_revision') #>> '{}')::numeric = trunc(((("fleet_automatic_receipt"."receipt"->'command')->'expected_revision') #>> '{}')::numeric) AND ((("fleet_automatic_receipt"."receipt"->'command')->'expected_revision') #>> '{}')::numeric BETWEEN 0 AND 9007199254740991 ELSE false END))) IS TRUE AND (((jsonb_typeof(("fleet_automatic_receipt"."receipt"->'result')) = 'object' AND ("fleet_automatic_receipt"."receipt"->'result') ?& ARRAY['generation', 'revision', 'enabled', 'approving_device_id', 'approved_at', 'disabled_at', 'closed_reason']::text[] AND ("fleet_automatic_receipt"."receipt"->'result') - ARRAY['generation', 'revision', 'enabled', 'approving_device_id', 'approved_at', 'disabled_at', 'closed_reason']::text[] = '{}'::jsonb) AND
    (CASE WHEN jsonb_typeof((("fleet_automatic_receipt"."receipt"->'result')->'generation')) = 'number' THEN ((("fleet_automatic_receipt"."receipt"->'result')->'generation') #>> '{}')::numeric = trunc(((("fleet_automatic_receipt"."receipt"->'result')->'generation') #>> '{}')::numeric) AND ((("fleet_automatic_receipt"."receipt"->'result')->'generation') #>> '{}')::numeric BETWEEN 0 AND 9007199254740991 ELSE false END) AND (CASE WHEN jsonb_typeof((("fleet_automatic_receipt"."receipt"->'result')->'revision')) = 'number' THEN ((("fleet_automatic_receipt"."receipt"->'result')->'revision') #>> '{}')::numeric = trunc(((("fleet_automatic_receipt"."receipt"->'result')->'revision') #>> '{}')::numeric) AND ((("fleet_automatic_receipt"."receipt"->'result')->'revision') #>> '{}')::numeric BETWEEN 0 AND 9007199254740991 ELSE false END) AND jsonb_typeof((("fleet_automatic_receipt"."receipt"->'result')->'enabled')) = 'boolean' AND
    (CASE WHEN (("fleet_automatic_receipt"."receipt"->'result')->'generation') = '0'::jsonb THEN (("fleet_automatic_receipt"."receipt"->'result')->'revision') = '0'::jsonb AND (("fleet_automatic_receipt"."receipt"->'result')->'enabled') = 'false'::jsonb AND (("fleet_automatic_receipt"."receipt"->'result')->'approving_device_id') = 'null'::jsonb AND (("fleet_automatic_receipt"."receipt"->'result')->'approved_at') = 'null'::jsonb AND (("fleet_automatic_receipt"."receipt"->'result')->'disabled_at') = 'null'::jsonb AND (("fleet_automatic_receipt"."receipt"->'result')->'closed_reason') = 'null'::jsonb
    ELSE (("fleet_automatic_receipt"."receipt"->'result')->'revision') >= (("fleet_automatic_receipt"."receipt"->'result')->'generation') AND (jsonb_typeof((("fleet_automatic_receipt"."receipt"->'result')->'approving_device_id')) = 'string' AND lower(((("fleet_automatic_receipt"."receipt"->'result')->'approving_device_id') #>> '{}')) ~ '^([0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$') AND (CASE WHEN jsonb_typeof((("fleet_automatic_receipt"."receipt"->'result')->'approved_at')) = 'string' AND ((("fleet_automatic_receipt"."receipt"->'result')->'approved_at') #>> '{}') ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}[.][0-9]{3}Z$' AND left(((("fleet_automatic_receipt"."receipt"->'result')->'approved_at') #>> '{}'), 4) <> '0000'
    THEN to_char(((("fleet_automatic_receipt"."receipt"->'result')->'approved_at') #>> '{}')::timestamptz AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') = ((("fleet_automatic_receipt"."receipt"->'result')->'approved_at') #>> '{}') ELSE false END) AND
      (CASE WHEN (("fleet_automatic_receipt"."receipt"->'result')->'enabled') = 'true'::jsonb THEN (("fleet_automatic_receipt"."receipt"->'result')->'revision') < '9007199254740991'::jsonb AND (("fleet_automatic_receipt"."receipt"->'result')->'disabled_at') = 'null'::jsonb AND (("fleet_automatic_receipt"."receipt"->'result')->'closed_reason') = 'null'::jsonb
       ELSE (CASE WHEN jsonb_typeof((("fleet_automatic_receipt"."receipt"->'result')->'disabled_at')) = 'string' AND ((("fleet_automatic_receipt"."receipt"->'result')->'disabled_at') #>> '{}') ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}[.][0-9]{3}Z$' AND left(((("fleet_automatic_receipt"."receipt"->'result')->'disabled_at') #>> '{}'), 4) <> '0000'
    THEN to_char(((("fleet_automatic_receipt"."receipt"->'result')->'disabled_at') #>> '{}')::timestamptz AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') = ((("fleet_automatic_receipt"."receipt"->'result')->'disabled_at') #>> '{}') ELSE false END) AND ((("fleet_automatic_receipt"."receipt"->'result')->'disabled_at') #>> '{}') >= ((("fleet_automatic_receipt"."receipt"->'result')->'approved_at') #>> '{}') AND (jsonb_typeof((("fleet_automatic_receipt"."receipt"->'result')->'closed_reason')) = 'string' AND ((("fleet_automatic_receipt"."receipt"->'result')->'closed_reason') #>> '{}') IN ('explicit_off', 'source_stop', 'approver_revoked')) END) END))) IS TRUE THEN
    ((CASE WHEN jsonb_typeof(("fleet_automatic_receipt"."receipt"->'accepted_at')) = 'string' AND (("fleet_automatic_receipt"."receipt"->'accepted_at') #>> '{}') ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}[.][0-9]{3}Z$' AND left((("fleet_automatic_receipt"."receipt"->'accepted_at') #>> '{}'), 4) <> '0000'
    THEN to_char((("fleet_automatic_receipt"."receipt"->'accepted_at') #>> '{}')::timestamptz AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') = (("fleet_automatic_receipt"."receipt"->'accepted_at') #>> '{}') ELSE false END) AND (CASE WHEN jsonb_typeof(("fleet_automatic_receipt"."receipt"->'expires_at')) = 'string' AND (("fleet_automatic_receipt"."receipt"->'expires_at') #>> '{}') ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}[.][0-9]{3}Z$' AND left((("fleet_automatic_receipt"."receipt"->'expires_at') #>> '{}'), 4) <> '0000'
    THEN to_char((("fleet_automatic_receipt"."receipt"->'expires_at') #>> '{}')::timestamptz AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') = (("fleet_automatic_receipt"."receipt"->'expires_at') #>> '{}') ELSE false END) AND
    (("fleet_automatic_receipt"."receipt"->'expires_at') #>> '{}')::timestamptz = (("fleet_automatic_receipt"."receipt"->'accepted_at') #>> '{}')::timestamptz + interval '24 hours' AND
    ((("fleet_automatic_receipt"."receipt"->'command')->'intent_created_at') #>> '{}') <= (("fleet_automatic_receipt"."receipt"->'accepted_at') #>> '{}') AND
    ((("fleet_automatic_receipt"."receipt"->'command')->'enabled') = 'false'::jsonb OR (("fleet_automatic_receipt"."receipt"->'accepted_at') #>> '{}')::timestamptz < ((("fleet_automatic_receipt"."receipt"->'command')->'intent_created_at') #>> '{}')::timestamptz + interval '60 seconds') AND
    ((("fleet_automatic_receipt"."receipt"->'result')->'approved_at') = 'null'::jsonb OR ((("fleet_automatic_receipt"."receipt"->'result')->'approved_at') #>> '{}') <= (("fleet_automatic_receipt"."receipt"->'accepted_at') #>> '{}')) AND ((("fleet_automatic_receipt"."receipt"->'result')->'disabled_at') = 'null'::jsonb OR ((("fleet_automatic_receipt"."receipt"->'result')->'disabled_at') #>> '{}') <= (("fleet_automatic_receipt"."receipt"->'accepted_at') #>> '{}'))) AND ((("fleet_automatic_receipt"."receipt"->'command')->'request_id') #>> '{}') = "fleet_automatic_receipt"."request_id"::text AND (("fleet_automatic_receipt"."receipt"->'expires_at') #>> '{}')::timestamptz = "fleet_automatic_receipt"."expires_at" AND
    (("fleet_automatic_receipt"."receipt"->'result')->'enabled') = (("fleet_automatic_receipt"."receipt"->'command')->'enabled') AND
    ((("fleet_automatic_receipt"."receipt"->'result')->'generation') #>> '{}')::numeric = ((("fleet_automatic_receipt"."receipt"->'command')->'expected_generation') #>> '{}')::numeric + CASE WHEN (("fleet_automatic_receipt"."receipt"->'command')->'enabled') = 'true'::jsonb THEN 1 ELSE 0 END AND
    ((("fleet_automatic_receipt"."receipt"->'result')->'revision') #>> '{}')::numeric = ((("fleet_automatic_receipt"."receipt"->'command')->'expected_revision') #>> '{}')::numeric + 1 AND
    ((("fleet_automatic_receipt"."receipt"->'command')->'enabled') = 'false'::jsonb OR ((("fleet_automatic_receipt"."receipt"->'result')->'revision') #>> '{}')::numeric <= 9007199254740990)
    ELSE false END) IS TRUE);--> statement-breakpoint
ALTER TABLE "fleet_source_intent" ADD CONSTRAINT "fleet_source_intent_stop_receipt_ck" CHECK ((NOT "fleet_source_intent"."explicitly_stopped" OR "fleet_source_intent"."state" = 'ended') AND ("fleet_source_intent"."stop_receipt" IS NULL OR ("fleet_source_intent"."explicitly_stopped" AND (CASE WHEN octet_length("fleet_source_intent"."stop_receipt"::text) <= 2048 AND
    (jsonb_typeof("fleet_source_intent"."stop_receipt") = 'object' AND "fleet_source_intent"."stop_receipt" ?& ARRAY['kind', 'command', 'accepted_at', 'expires_at', 'source', 'automatic_effect', 'consent']::text[] AND "fleet_source_intent"."stop_receipt" - ARRAY['kind', 'command', 'accepted_at', 'expires_at', 'source', 'automatic_effect', 'consent']::text[] = '{}'::jsonb) AND ("fleet_source_intent"."stop_receipt"->'kind') = '"source_stop"'::jsonb AND
    (((jsonb_typeof(("fleet_source_intent"."stop_receipt"->'command')) = 'object' AND ("fleet_source_intent"."stop_receipt"->'command') ?& ARRAY['protocol', 'operation', 'request_id', 'intent_created_at', 'source_id', 'expected_generation', 'expected_automatic']::text[] AND ("fleet_source_intent"."stop_receipt"->'command') - ARRAY['protocol', 'operation', 'request_id', 'intent_created_at', 'source_id', 'expected_generation', 'expected_automatic']::text[] = '{}'::jsonb) AND (("fleet_source_intent"."stop_receipt"->'command')->'protocol') = '2'::jsonb AND (jsonb_typeof((("fleet_source_intent"."stop_receipt"->'command')->'request_id')) = 'string' AND ((("fleet_source_intent"."stop_receipt"->'command')->'request_id') #>> '{}') ~ '^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$') AND (CASE WHEN jsonb_typeof((("fleet_source_intent"."stop_receipt"->'command')->'intent_created_at')) = 'string' AND ((("fleet_source_intent"."stop_receipt"->'command')->'intent_created_at') #>> '{}') ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}[.][0-9]{3}Z$' AND left(((("fleet_source_intent"."stop_receipt"->'command')->'intent_created_at') #>> '{}'), 4) <> '0000'
    THEN to_char(((("fleet_source_intent"."stop_receipt"->'command')->'intent_created_at') #>> '{}')::timestamptz AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') = ((("fleet_source_intent"."stop_receipt"->'command')->'intent_created_at') #>> '{}') ELSE false END) AND
    (CASE WHEN jsonb_typeof((("fleet_source_intent"."stop_receipt"->'command')->'expected_generation')) = 'number' THEN ((("fleet_source_intent"."stop_receipt"->'command')->'expected_generation') #>> '{}')::numeric = trunc(((("fleet_source_intent"."stop_receipt"->'command')->'expected_generation') #>> '{}')::numeric) AND ((("fleet_source_intent"."stop_receipt"->'command')->'expected_generation') #>> '{}')::numeric BETWEEN 0 AND 2147483646 ELSE false END) AND
    (("fleet_source_intent"."stop_receipt"->'command')->'operation') = '"stop"'::jsonb AND (jsonb_typeof((("fleet_source_intent"."stop_receipt"->'command')->'source_id')) = 'string' AND lower(((("fleet_source_intent"."stop_receipt"->'command')->'source_id') #>> '{}')) ~ '^([0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$') AND ((("fleet_source_intent"."stop_receipt"->'command')->'expected_automatic') = 'null'::jsonb OR (jsonb_typeof((("fleet_source_intent"."stop_receipt"->'command')->'expected_automatic')) = 'object' AND (("fleet_source_intent"."stop_receipt"->'command')->'expected_automatic') ?& ARRAY['consent_generation']::text[] AND (("fleet_source_intent"."stop_receipt"->'command')->'expected_automatic') - ARRAY['consent_generation']::text[] = '{}'::jsonb) AND (CASE WHEN jsonb_typeof(((("fleet_source_intent"."stop_receipt"->'command')->'expected_automatic')->'consent_generation')) = 'number' THEN (((("fleet_source_intent"."stop_receipt"->'command')->'expected_automatic')->'consent_generation') #>> '{}')::numeric = trunc((((("fleet_source_intent"."stop_receipt"->'command')->'expected_automatic')->'consent_generation') #>> '{}')::numeric) AND (((("fleet_source_intent"."stop_receipt"->'command')->'expected_automatic')->'consent_generation') #>> '{}')::numeric BETWEEN 1 AND 9007199254740991 ELSE false END)))) IS TRUE AND (((jsonb_typeof(("fleet_source_intent"."stop_receipt"->'source')) = 'object' AND ("fleet_source_intent"."stop_receipt"->'source') ?& ARRAY['source_id', 'generation', 'character_id', 'state', 'reason', 'pending_expires_at', 'automatic']::text[] AND ("fleet_source_intent"."stop_receipt"->'source') - ARRAY['source_id', 'generation', 'character_id', 'state', 'reason', 'pending_expires_at', 'automatic']::text[] = '{}'::jsonb) AND
    (jsonb_typeof((("fleet_source_intent"."stop_receipt"->'source')->'source_id')) = 'string' AND lower(((("fleet_source_intent"."stop_receipt"->'source')->'source_id') #>> '{}')) ~ '^([0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$') AND (CASE WHEN jsonb_typeof((("fleet_source_intent"."stop_receipt"->'source')->'generation')) = 'number' THEN ((("fleet_source_intent"."stop_receipt"->'source')->'generation') #>> '{}')::numeric = trunc(((("fleet_source_intent"."stop_receipt"->'source')->'generation') #>> '{}')::numeric) AND ((("fleet_source_intent"."stop_receipt"->'source')->'generation') #>> '{}')::numeric BETWEEN 1 AND 2147483647 ELSE false END) AND
    ((("fleet_source_intent"."stop_receipt"->'source')->'character_id') = 'null'::jsonb OR (CASE WHEN jsonb_typeof((("fleet_source_intent"."stop_receipt"->'source')->'character_id')) = 'number' THEN ((("fleet_source_intent"."stop_receipt"->'source')->'character_id') #>> '{}')::numeric = trunc(((("fleet_source_intent"."stop_receipt"->'source')->'character_id') #>> '{}')::numeric) AND ((("fleet_source_intent"."stop_receipt"->'source')->'character_id') #>> '{}')::numeric BETWEEN 1 AND 9007199254740991 ELSE false END)) AND
    (("fleet_source_intent"."stop_receipt"->'source')->'state') = '"ended"'::jsonb AND (("fleet_source_intent"."stop_receipt"->'source')->'pending_expires_at') = 'null'::jsonb AND
    (jsonb_typeof((("fleet_source_intent"."stop_receipt"->'source')->'reason')) = 'string' AND ((("fleet_source_intent"."stop_receipt"->'source')->'reason') #>> '{}') IN ('stopped', 'expired', 'superseded', 'not_in_fleet', 'boss_lost', 'identity_changed', 'fleet_read_invalid', 'member_lost', 'device_revoked', 'token_invalid', 'mode_transition', 'service_unavailable', 'untrustworthy_evidence', 'timed_out', 'ended')) AND
    ((("fleet_source_intent"."stop_receipt"->'source')->'automatic') = 'null'::jsonb OR (jsonb_typeof((("fleet_source_intent"."stop_receipt"->'source')->'automatic')) = 'object' AND (("fleet_source_intent"."stop_receipt"->'source')->'automatic') ?& ARRAY['consent_generation']::text[] AND (("fleet_source_intent"."stop_receipt"->'source')->'automatic') - ARRAY['consent_generation']::text[] = '{}'::jsonb) AND (CASE WHEN jsonb_typeof(((("fleet_source_intent"."stop_receipt"->'source')->'automatic')->'consent_generation')) = 'number' THEN (((("fleet_source_intent"."stop_receipt"->'source')->'automatic')->'consent_generation') #>> '{}')::numeric = trunc((((("fleet_source_intent"."stop_receipt"->'source')->'automatic')->'consent_generation') #>> '{}')::numeric) AND (((("fleet_source_intent"."stop_receipt"->'source')->'automatic')->'consent_generation') #>> '{}')::numeric BETWEEN 1 AND 9007199254740991 ELSE false END)))) IS TRUE AND (((jsonb_typeof(("fleet_source_intent"."stop_receipt"->'consent')) = 'object' AND ("fleet_source_intent"."stop_receipt"->'consent') ?& ARRAY['generation', 'revision', 'enabled', 'approving_device_id', 'approved_at', 'disabled_at', 'closed_reason']::text[] AND ("fleet_source_intent"."stop_receipt"->'consent') - ARRAY['generation', 'revision', 'enabled', 'approving_device_id', 'approved_at', 'disabled_at', 'closed_reason']::text[] = '{}'::jsonb) AND
    (CASE WHEN jsonb_typeof((("fleet_source_intent"."stop_receipt"->'consent')->'generation')) = 'number' THEN ((("fleet_source_intent"."stop_receipt"->'consent')->'generation') #>> '{}')::numeric = trunc(((("fleet_source_intent"."stop_receipt"->'consent')->'generation') #>> '{}')::numeric) AND ((("fleet_source_intent"."stop_receipt"->'consent')->'generation') #>> '{}')::numeric BETWEEN 0 AND 9007199254740991 ELSE false END) AND (CASE WHEN jsonb_typeof((("fleet_source_intent"."stop_receipt"->'consent')->'revision')) = 'number' THEN ((("fleet_source_intent"."stop_receipt"->'consent')->'revision') #>> '{}')::numeric = trunc(((("fleet_source_intent"."stop_receipt"->'consent')->'revision') #>> '{}')::numeric) AND ((("fleet_source_intent"."stop_receipt"->'consent')->'revision') #>> '{}')::numeric BETWEEN 0 AND 9007199254740991 ELSE false END) AND jsonb_typeof((("fleet_source_intent"."stop_receipt"->'consent')->'enabled')) = 'boolean' AND
    (CASE WHEN (("fleet_source_intent"."stop_receipt"->'consent')->'generation') = '0'::jsonb THEN (("fleet_source_intent"."stop_receipt"->'consent')->'revision') = '0'::jsonb AND (("fleet_source_intent"."stop_receipt"->'consent')->'enabled') = 'false'::jsonb AND (("fleet_source_intent"."stop_receipt"->'consent')->'approving_device_id') = 'null'::jsonb AND (("fleet_source_intent"."stop_receipt"->'consent')->'approved_at') = 'null'::jsonb AND (("fleet_source_intent"."stop_receipt"->'consent')->'disabled_at') = 'null'::jsonb AND (("fleet_source_intent"."stop_receipt"->'consent')->'closed_reason') = 'null'::jsonb
    ELSE (("fleet_source_intent"."stop_receipt"->'consent')->'revision') >= (("fleet_source_intent"."stop_receipt"->'consent')->'generation') AND (jsonb_typeof((("fleet_source_intent"."stop_receipt"->'consent')->'approving_device_id')) = 'string' AND lower(((("fleet_source_intent"."stop_receipt"->'consent')->'approving_device_id') #>> '{}')) ~ '^([0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$') AND (CASE WHEN jsonb_typeof((("fleet_source_intent"."stop_receipt"->'consent')->'approved_at')) = 'string' AND ((("fleet_source_intent"."stop_receipt"->'consent')->'approved_at') #>> '{}') ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}[.][0-9]{3}Z$' AND left(((("fleet_source_intent"."stop_receipt"->'consent')->'approved_at') #>> '{}'), 4) <> '0000'
    THEN to_char(((("fleet_source_intent"."stop_receipt"->'consent')->'approved_at') #>> '{}')::timestamptz AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') = ((("fleet_source_intent"."stop_receipt"->'consent')->'approved_at') #>> '{}') ELSE false END) AND
      (CASE WHEN (("fleet_source_intent"."stop_receipt"->'consent')->'enabled') = 'true'::jsonb THEN (("fleet_source_intent"."stop_receipt"->'consent')->'revision') < '9007199254740991'::jsonb AND (("fleet_source_intent"."stop_receipt"->'consent')->'disabled_at') = 'null'::jsonb AND (("fleet_source_intent"."stop_receipt"->'consent')->'closed_reason') = 'null'::jsonb
       ELSE (CASE WHEN jsonb_typeof((("fleet_source_intent"."stop_receipt"->'consent')->'disabled_at')) = 'string' AND ((("fleet_source_intent"."stop_receipt"->'consent')->'disabled_at') #>> '{}') ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}[.][0-9]{3}Z$' AND left(((("fleet_source_intent"."stop_receipt"->'consent')->'disabled_at') #>> '{}'), 4) <> '0000'
    THEN to_char(((("fleet_source_intent"."stop_receipt"->'consent')->'disabled_at') #>> '{}')::timestamptz AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') = ((("fleet_source_intent"."stop_receipt"->'consent')->'disabled_at') #>> '{}') ELSE false END) AND ((("fleet_source_intent"."stop_receipt"->'consent')->'disabled_at') #>> '{}') >= ((("fleet_source_intent"."stop_receipt"->'consent')->'approved_at') #>> '{}') AND (jsonb_typeof((("fleet_source_intent"."stop_receipt"->'consent')->'closed_reason')) = 'string' AND ((("fleet_source_intent"."stop_receipt"->'consent')->'closed_reason') #>> '{}') IN ('explicit_off', 'source_stop', 'approver_revoked')) END) END))) IS TRUE THEN
    ((CASE WHEN jsonb_typeof(("fleet_source_intent"."stop_receipt"->'accepted_at')) = 'string' AND (("fleet_source_intent"."stop_receipt"->'accepted_at') #>> '{}') ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}[.][0-9]{3}Z$' AND left((("fleet_source_intent"."stop_receipt"->'accepted_at') #>> '{}'), 4) <> '0000'
    THEN to_char((("fleet_source_intent"."stop_receipt"->'accepted_at') #>> '{}')::timestamptz AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') = (("fleet_source_intent"."stop_receipt"->'accepted_at') #>> '{}') ELSE false END) AND (CASE WHEN jsonb_typeof(("fleet_source_intent"."stop_receipt"->'expires_at')) = 'string' AND (("fleet_source_intent"."stop_receipt"->'expires_at') #>> '{}') ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}[.][0-9]{3}Z$' AND left((("fleet_source_intent"."stop_receipt"->'expires_at') #>> '{}'), 4) <> '0000'
    THEN to_char((("fleet_source_intent"."stop_receipt"->'expires_at') #>> '{}')::timestamptz AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') = (("fleet_source_intent"."stop_receipt"->'expires_at') #>> '{}') ELSE false END) AND
    (("fleet_source_intent"."stop_receipt"->'expires_at') #>> '{}')::timestamptz = (("fleet_source_intent"."stop_receipt"->'accepted_at') #>> '{}')::timestamptz + interval '24 hours' AND
    ((("fleet_source_intent"."stop_receipt"->'command')->'intent_created_at') #>> '{}') <= (("fleet_source_intent"."stop_receipt"->'accepted_at') #>> '{}') AND
    ( (("fleet_source_intent"."stop_receipt"->'accepted_at') #>> '{}')::timestamptz < ((("fleet_source_intent"."stop_receipt"->'command')->'intent_created_at') #>> '{}')::timestamptz + interval '60 seconds') AND
    ((("fleet_source_intent"."stop_receipt"->'consent')->'approved_at') = 'null'::jsonb OR ((("fleet_source_intent"."stop_receipt"->'consent')->'approved_at') #>> '{}') <= (("fleet_source_intent"."stop_receipt"->'accepted_at') #>> '{}')) AND ((("fleet_source_intent"."stop_receipt"->'consent')->'disabled_at') = 'null'::jsonb OR ((("fleet_source_intent"."stop_receipt"->'consent')->'disabled_at') #>> '{}') <= (("fleet_source_intent"."stop_receipt"->'accepted_at') #>> '{}'))) AND lower(((("fleet_source_intent"."stop_receipt"->'command')->'source_id') #>> '{}')) = "fleet_source_intent"."id"::text AND lower(((("fleet_source_intent"."stop_receipt"->'source')->'source_id') #>> '{}')) = "fleet_source_intent"."id"::text AND
    ((("fleet_source_intent"."stop_receipt"->'source')->'generation') #>> '{}')::numeric = "fleet_source_intent"."generation" AND (("fleet_source_intent"."stop_receipt"->'command')->'expected_automatic') = (("fleet_source_intent"."stop_receipt"->'source')->'automatic') AND
    (("fleet_source_intent"."automatic_consent_generation" IS NULL AND (("fleet_source_intent"."stop_receipt"->'source')->'automatic') = 'null'::jsonb) OR ("fleet_source_intent"."automatic_consent_generation" IS NOT NULL AND (((("fleet_source_intent"."stop_receipt"->'source')->'automatic')->'consent_generation') #>> '{}')::numeric = "fleet_source_intent"."automatic_consent_generation")) AND
    "fleet_source_intent"."retain_until" >= (("fleet_source_intent"."stop_receipt"->'expires_at') #>> '{}')::timestamptz AND
    (CASE WHEN ("fleet_source_intent"."stop_receipt"->'automatic_effect') = '"unknown_cancelled"'::jsonb THEN ((("fleet_source_intent"."stop_receipt"->'command')->'expected_generation') #>> '{}')::numeric = 0 AND (("fleet_source_intent"."stop_receipt"->'source')->'automatic') = 'null'::jsonb AND ((("fleet_source_intent"."stop_receipt"->'source')->'generation') #>> '{}')::numeric = 1
    ELSE ((("fleet_source_intent"."stop_receipt"->'command')->'expected_generation') #>> '{}')::numeric > 0 AND ((("fleet_source_intent"."stop_receipt"->'source')->'generation') #>> '{}')::numeric BETWEEN ((("fleet_source_intent"."stop_receipt"->'command')->'expected_generation') #>> '{}')::numeric AND ((("fleet_source_intent"."stop_receipt"->'command')->'expected_generation') #>> '{}')::numeric + 1 AND
      (CASE WHEN ("fleet_source_intent"."stop_receipt"->'automatic_effect') = '"manual_only"'::jsonb THEN (("fleet_source_intent"."stop_receipt"->'source')->'automatic') = 'null'::jsonb
       WHEN ("fleet_source_intent"."stop_receipt"->'automatic_effect') IN ('"disabled_current"'::jsonb, '"current_already_off"'::jsonb) THEN (((("fleet_source_intent"."stop_receipt"->'source')->'automatic')->'consent_generation') #>> '{}')::numeric = ((("fleet_source_intent"."stop_receipt"->'consent')->'generation') #>> '{}')::numeric AND (("fleet_source_intent"."stop_receipt"->'consent')->'enabled') = 'false'::jsonb
       WHEN ("fleet_source_intent"."stop_receipt"->'automatic_effect') = '"older_generation_only"'::jsonb THEN (((("fleet_source_intent"."stop_receipt"->'source')->'automatic')->'consent_generation') #>> '{}')::numeric < ((("fleet_source_intent"."stop_receipt"->'consent')->'generation') #>> '{}')::numeric ELSE false END) END)
    ELSE false END) IS TRUE)));